apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
spec:
  containers:
  - name: app-livenessprob
    image: gcr.io/k8s-k3s/demo:v1.0.0
    livenessProbe:
      httpGet:
        path: /
        port: ports
      initialDelaySeconds: 15
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    ports:
    - containerPort: ports