apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  containers:
  - name: main
    image: nginx
  - name: sidecar
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Hello from the sidecar container"; sleep 10; done']